version: 0.2

env:
  variables:
    BUILD_TFM: 'net6.0'
    BUILD_CONFIGURATION: 'Release'
    RESTORE_OUTPUT_PATH: 'packages'
    REPORTS_PATH: 'test-results'
    PROJECT_NAME: 'Allure.Net.Examples.xUnit.Tests'
    REPORT_DOTNET_COMMAND: '--logger:"trx;LogFileName=../bin/Release/net6.0/test-results/report.trx"'
  exported-variables:
    - BUILD_TFM
    - BUILD_CONFIGURATION
    - RESTORE_OUTPUT_PATH
    - REPORTS_PATH
    - PROJECT_NAME
    - REPORT_DOTNET_COMMAND
    - ALLURE_ENDPOINT
    - ALLURE_PROJECT_ID
    - ALLURE_TOKEN

phases:
  install:
    commands:
      - echo "Install .NET 6.0 LTS Release"
      - /usr/local/bin/dotnet-install.sh --channel LTS
      - echo "Install Allure commandline"
      - wget https://github.com/allure-framework/allure2/releases/download/2.18.1/allure_2.18.1-1_all.deb
      - dpkg -i allure_2.18.1-1_all.deb
      - apt-get install -f
      - echo "Install allurectl"
      - wget https://github.com/allure-framework/allurectl/releases/latest/download/allurectl_linux_386 -O ./allurectl
      - chmod +x ./allurectl
  pre_build:
    commands:
      - printenv
#     - export ALLURE_LAUNCH_NAME="$CODEBUILD_BUILD_ID"
      - echo "Start Dummy Application for testing"
      - nohup $CODEBUILD_SRC_DIR_DummyApplication/Dummy.App & echo $! > dummypid
  build:
    commands:
      - dotnet restore ./$PROJECT_NAME/$PROJECT_NAME.csproj --packages $RESTORE_OUTPUT_PATH -p:TargetFramework=$BUILD_TFM
      - dotnet build ./$PROJECT_NAME/$PROJECT_NAME.csproj --no-restore --framework $BUILD_TFM --configuration $BUILD_CONFIGURATION
      - ./allurectl watch --results ./$PROJECT_NAME/bin/$BUILD_CONFIGURATION/$BUILD_TFM/allure-results -- dotnet test ./$PROJECT_NAME/$PROJECT_NAME.csproj --no-restore --framework $BUILD_TFM --configuration $BUILD_CONFIGURATION $REPORT_DOTNET_COMMAND
    finally:
      - echo "Kill Dummy Application"
      - kill $(cat dummypid)
#      - allure generate --clean ./$PROJECT_NAME/bin/$BUILD_CONFIGURATION/$BUILD_TFM/allure-results

reports:
  generated-reports:
    base-directory: ./$PROJECT_NAME/bin/$BUILD_CONFIGURATION/$BUILD_TFM/$REPORTS_PATH
    discard-paths: no
    files:
      - '**/*'
    file-format: VISUALSTUDIOTRX
#    file-format: $REPORT_FORMAT

artifacts:
  base-directory: allure-report
  files:
    - '**/*'
